apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-nfs-pvc
  namespace: kubeflow-user-example-com
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # same to pv
# kubectl apply -f nas-nfs-pvc.yaml
